### ISSUE TITLE
As an admin, I want to add a Chrome Extension page and callout box

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree.js.org#12]
Let's start shifting into startup gear!

## Tasks
- [x] Create the `/chrome` route
- [x] Create a callout to get emails for launch
- [x] Hook up the box to a tool like mailchimp
- [x] Add content

## Extras
- [x] Isolate Aframe/Fireworks logic into a reusable component for JS Home and Extension Landing
