### ISSUE TITLE
As a user, I want to type via a virtual keyboard

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree.js.org#5]
Let's use SimpleKeyboard to enable typing handsfree!

## Tasks
- [x] Create the `keyboard` route
- [x] Add the virtual keyboard
- [ ] Add different keyboard layouts (letters, digits, emojis)

## Story Cleanup
- [ ] Create post on Dev.to
