### ISSUE TITLE
As a user, I want to paint with my face

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree.js.org#6]
This story involves getting a P5.js sketch working alongside Handsfree.js. The goal is to draw with your face and the purpose is to cover clicking and integration.

## Tasks
- [x] Create the route
- [x] Import P5
- [x] Create the sketch so that it draws a lines when on click mode
- [x] Two colors: smile left and right

## Story cleanup
- [ ] Create Sketch on P5
- [ ] Create Dev.to tutorial
