### ISSUE TITLE
As a User, I want to control a 1st Person game with my head

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree.js.org#7]
This story explores the `handsfree.head.position` properties to move a player in 3D space.

## Tasks
- [x] Create the `1st-person` route
- [x] Load the [Three.js example](https://threejs.org/examples/#misc_controls_pointerlock)
- [x] When leaning, move in that direction
- [x] When turning head, turn POV in that direction
- [x] When raising eyebrows, jump
- [ ] Refactor and clean up the code

## Cleanup
- [ ] Break out the `handsfree.use` code for each route into it's own file, so that we can link readers to it for studying
- [ ] Write a tutorial on Dev.to
- [ ] Add links to docs
- [ ] Add tweet to home page
